"""Generate synthetic distorted flatcam footage plus matching profile and venue."""
from __future__ import annotations

import argparse, json
from datetime import datetime, timezone
from pathlib import Path

import cv2
import numpy as np


def distort(frame, strength=0.35):
    h, w = frame.shape[:2]
    cx, cy = (w - 1) / 2, (h - 1) / 2
    xs, ys = np.meshgrid(np.arange(w, dtype=np.float32), np.arange(h, dtype=np.float32))
    x, y = (xs - cx) / cx, (ys - cy) / cy
    r2 = x*x + y*y
    scale = 1 + strength * r2
    return cv2.remap(frame, (cx + (xs-cx)*scale).astype(np.float32), (cy + (ys-cy)*scale).astype(np.float32), cv2.INTER_LINEAR)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", default="flatcam/test_clip.mp4")
    ap.add_argument("--profile-out", default="flatcam/test_lens_profiles.json")
    ap.add_argument("--venue-out", default="flatcam/venues/synthetic.json")
    ap.add_argument("--frames", type=int, default=180)
    args = ap.parse_args()
    w, h, fps = 640, 360, 30
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    writer = cv2.VideoWriter(args.output, cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))
    for i in range(args.frames):
        frame = np.full((h, w, 3), (35, 120, 35), np.uint8)
        cv2.rectangle(frame, (50, 45), (590, 315), (55, 150, 55), -1)
        cv2.rectangle(frame, (50, 45), (590, 315), (230, 230, 230), 2)
        active = i < 75 or i > 125
        if active:
            base_x = int(110 + (i % 100) * 4.1)
            for j, dy in enumerate([-25, 0, 28]):
                cv2.circle(frame, (min(560, base_x + j*22), 180 + dy), 14, (245, 245, 245), -1)
        writer.write(distort(frame))
    writer.release()
    profile = [{"profile_name":"synthetic_flatcam_test","resolution":[w,h],"fov_deg":155,"projection":"equidistant","distortion_correction_strength":0.55,"calibration_status":"approximate","notes":"Synthetic test profile generated by make_test_clip.py."}]
    json.dump(profile, open(args.profile_out, "w", encoding="utf-8"), indent=2)
    venue = {"profile_name":"synthetic_flatcam_test","polygon":[[50,45],[590,45],[590,315],[50,315]],"created":datetime.now(timezone.utc).isoformat()}
    Path(args.venue_out).parent.mkdir(parents=True, exist_ok=True)
    json.dump(venue, open(args.venue_out, "w", encoding="utf-8"), indent=2)
    print(args.output); print(args.profile_out); print(args.venue_out)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
