#!/usr/bin/env python3
"""Offline 4-tier camera target_yaw fusion (playcam).

CORRECTED 6 July 2026: this version takes its ball-lock signal from the
EXISTING, established ball tracker's own Stage 2 output (tracklets.json,
status=="anchor") -- NOT from raw MOG2 candidates. An earlier version of
this script built its own confidence/geometry/persistence/continuity logic
directly on raw mog2_candidates.json; that bypassed the actual ball tracker
entirely and re-implemented (poorly) something the tracker's own Stage 2
linker already does properly. That approach is retired. Player-flow's job
is to sit ON TOP of the established tracker as an ahead-of-play framing
signal -- not to compete with it or be used to second-guess it.

The ball tracker itself (ball_tracker/run_tracker.py, stage2_temporal_link.py,
and everything else under Frozen tracker boundaries in
docs/ai-project-state.md) is NOT modified, NOT re-run, and NOT diagnosed by
this script. This script only *reads* its already-produced, already-frozen
Stage 2 output (tracklets.json) and trusts its own status field as-is.

Priority order (highest first):
  1. Ball-lock        -- a status=="anchor" tracklet (the tracker's own
                         Stage 2 linker's highest-quality tier: >=8
                         observations, mean confidence >=0.20, coverage
                         >=0.50, anchor_strength >=0.55 -- these thresholds
                         are stage2_temporal_link.py's own, unmodified,
                         reused verbatim) has a directly-observed frame in
                         this sample's window. target_yaw = that anchor's
                         yaw, PLUS a small ahead-of-play lead offset in the
                         sustained flow direction, if flow is sustained
                         (bounded, conservative -- see TIER1_LEAD_OFFSET_DEG).
  2. Flow-hold         -- an anchor was seen recently (within
                         --hold-max-samples) but isn't in this window; hold
                         near the last anchor yaw, nudged by current flow
                         direction if present, rather than reverting to
                         centroid immediately.
  3. Flow-only bias    -- no recent anchor, but the player-flow signal
                         shows *sustained* multi-track agreement; nudge
                         centroid yaw gently in that direction.
  4. Centroid fallback -- none of the above; person_centroid_yaw as-is.

A final light exponential smoothing pass is applied across the whole
target_yaw sequence (circular-safe) to damp step changes at tier
transitions -- see SMOOTHING_ALPHA.

Inputs:
  - tracklets.json     (ball_tracker Stage 2 output, e.g. artifact 7944978610
                        from run 28355256427 -- already computed, already
                        committed-adjacent evidence in docs/ai-project-state.md;
                        NOT regenerated by this script, zero paid compute)
  - play_location.jsonl (playcam/play_location.py output)

This script imports and reuses rather than duplicating:
  - playcam.player_flow_bias.compute_flow_signal()  (direction/sustain)

Decision cadence matches play_location.jsonl's native ~2Hz sampling, not
full video frame rate -- this remains an offline logic check, not a
per-frame render signal. Wiring into an actual per-frame render, and
whether the two source files truly share an identical frame clock, are
both explicitly NOT verified here -- see docs/ai-project-state.md for the
alignment assumption this relies on (same ~2-minute source clip, frame
range 6-3596 in both, CLIP_FPS shared).
"""
import argparse
import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from playcam.player_flow_bias import compute_flow_signal, load_records as load_play_location  # noqa: E402

CLIP_FPS = 3596 / 120.0  # shared assumption with mog2/tracklet frame range 6-3596 for this clip

# --- Tier 1: ball-lock (from the established tracker's own Stage 2 anchors) ---
# ANCHOR_STATUSES intentionally does not include "passing" (96 tracklets that
# cleared Stage 2's linker but were never individually adjudicated) or
# "fragment" (255, Stage 2's own rejects). "anchor" is Stage 2's strictest,
# pre-existing category (stage2_temporal_link.py: MIN_OBS_FOR_ANCHOR=8,
# MIN_MEAN_CONF_FOR_ANCHOR=0.20, MIN_COVERAGE_FOR_ANCHOR=0.50,
# MIN_ANCHOR_STRENGTH=0.55) and the only category Johnson has directly
# adjudicated (20/25 judged likely-ball -- i.e. even this tier is ~80%
# precision, not 100%; that residual uncertainty is the tracker's own, not
# introduced by this script).
ANCHOR_STATUSES = ("anchor",)

# Small, bounded ahead-of-play lead added ON TOP of a trusted anchor position
# when flow is sustained. Deliberately the smallest of the three nudges --
# we already have a precise, human-partially-vetted position here, so flow
# should only ever lean it slightly toward where play is developing, never
# override it.
TIER1_LEAD_OFFSET_DEG = 3.0

# --- Tier 2: flow-hold -----------------------------------------------------
# How many ~2Hz samples (~0.5s each) to keep holding near the last known
# anchor position after it disappears, before giving up on it entirely.
# Unchanged from the prior version's reasoning: conservative, ~2s, well
# short of the ~13s flow-only build-up seen in this clip's t=41-54s window.
HOLD_MAX_SAMPLES = 4
HOLD_FLOW_NUDGE_DEG = 2.0

# --- Tier 3: flow-only bias -------------------------------------------------
# Real sustained-sample mean_delta_yaw_deg values in this clip mostly fall
# in the ~1.5-5 deg/sample range (see player_flow_bias.py validation notes
# in docs/ai-project-state.md). Largest of the three nudges: this is the
# ONLY signal available when there's no anchor evidence at all.
FLOW_BIAS_NUDGE_DEG = 4.0

# Final smoothing pass, applied to the whole target_yaw sequence regardless
# of tier, to damp step changes at tier transitions. alpha=0.35 reuses the
# same EMA precedent already used elsewhere in this project's camera-bias
# smoothing (activity bias, prior session) -- a reasonable starting point,
# not tuned to this clip's specific goal.
SMOOTHING_ALPHA = 0.35


def circular_delta(a, b):
    return ((a - b + 180) % 360) - 180


def load_anchor_lookup(tracklets_path, anchor_statuses=ANCHOR_STATUSES):
    """Frame-indexed lookup of directly-observed anchor-tracklet positions.
    Returns dict: frame_idx -> list of (yaw, weighted_conf). Only frames
    actually present in a tracklet's `frames` list are used -- no
    interpolation/extrapolation within a tracklet's span, so coverage is
    honestly sparse rather than manufactured.
    """
    data = json.loads(Path(tracklets_path).read_text(encoding="utf-8"))
    lookup = {}
    for t in data["tracklets"]:
        if t["status"] not in anchor_statuses:
            continue
        for obs in t["frames"]:
            f = obs["frame"]
            lookup.setdefault(f, []).append((obs["yaw"], obs.get("weighted_conf", 0.0)))
    return lookup


def sample_anchor_for_window(anchor_lookup, frame_lo, frame_hi):
    """Highest-confidence anchor observation within [frame_lo, frame_hi],
    or None. No additional continuity/persistence gating is applied here --
    Stage 2's own linker already established these as coherent tracklets;
    re-gating them would be exactly the kind of second-guessing of the
    established tracker this revision is meant to stop doing.
    """
    best = None
    for f in range(frame_lo, frame_hi + 1):
        for (yaw, conf) in anchor_lookup.get(f, []):
            if best is None or conf > best[1]:
                best = (yaw, conf)
    return best


def run_fusion(tracklets_path, play_location_path, args):
    anchor_lookup = load_anchor_lookup(tracklets_path)

    records = load_play_location(play_location_path)
    flow_rows = compute_flow_signal(
        records, args.min_moving_vel, args.min_agreeing_tracks, args.min_sustain_samples
    )
    flow_by_ts = {round(r["timestamp"], 3): r for r in flow_rows}

    raw_rows = []
    last_ball_yaw = None
    samples_since_ball = None  # None until the first anchor is ever seen
    prev_t = 0.0

    for i, rec in enumerate(records):
        t = rec["timestamp"]
        centroid_yaw = rec.get("person_centroid_yaw")
        flow = flow_by_ts.get(round(t, 3), {})
        flow_dir = int(flow.get("direction", 0))
        flow_sustained = int(flow.get("sustained", 0))

        frame_lo = 0 if i == 0 else int(round(prev_t * CLIP_FPS)) + 1
        frame_hi = int(round(t * CLIP_FPS))
        if frame_hi < frame_lo:
            frame_hi = frame_lo
        anchor_hit = sample_anchor_for_window(anchor_lookup, frame_lo, frame_hi)

        ball_conf = ""
        if anchor_hit is not None:
            tier = 1
            anchor_yaw, conf = anchor_hit
            ball_conf = round(conf, 3)
            lead = args.tier1_lead_offset_deg * flow_dir if flow_sustained else 0.0
            target_yaw = ((anchor_yaw + lead + 180) % 360) - 180
            last_ball_yaw = anchor_yaw
            samples_since_ball = 0
        elif (
            samples_since_ball is not None
            and samples_since_ball < args.hold_max_samples
            and last_ball_yaw is not None
        ):
            tier = 2
            samples_since_ball += 1
            nudge = args.hold_flow_nudge_deg * flow_dir
            target_yaw = ((last_ball_yaw + nudge + 180) % 360) - 180
        elif flow_sustained and flow_dir != 0 and centroid_yaw is not None:
            tier = 3
            nudge = args.flow_bias_nudge_deg * flow_dir
            target_yaw = ((centroid_yaw + nudge + 180) % 360) - 180
            if samples_since_ball is not None:
                samples_since_ball += 1
        else:
            tier = 4
            target_yaw = centroid_yaw
            if samples_since_ball is not None:
                samples_since_ball += 1

        raw_rows.append(
            {
                "timestamp": t,
                "tier": tier,
                "target_yaw": target_yaw,
                "centroid_yaw": centroid_yaw,
                "flow_direction": flow_dir,
                "flow_sustained": flow_sustained,
                "flow_agreeing_tracks": flow.get("agreeing_tracks", 0),
                "ball_conf": ball_conf,
                "last_ball_yaw": round(last_ball_yaw, 2) if last_ball_yaw is not None else "",
                "samples_since_ball": samples_since_ball if samples_since_ball is not None else "",
            }
        )
        prev_t = t

    # Final circular-safe EMA smoothing pass over target_yaw.
    smoothed = None
    for row in raw_rows:
        ty = row["target_yaw"]
        if ty is None:
            row["target_yaw"] = ""
            row["target_yaw_smoothed"] = round(smoothed, 2) if smoothed is not None else ""
            continue
        if smoothed is None:
            smoothed = ty
        else:
            smoothed = smoothed + circular_delta(ty, smoothed) * args.smoothing_alpha
            smoothed = ((smoothed + 180) % 360) - 180
        row["target_yaw"] = round(ty, 2)
        row["target_yaw_smoothed"] = round(smoothed, 2)

    return raw_rows


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("tracklets", help="Stage 2 tracklets.json from the established ball tracker")
    p.add_argument("play_location", help="play_location.jsonl (from play_location.py)")
    p.add_argument("--output", default="fusion_target_yaw.csv")
    p.add_argument("--tier1-lead-offset-deg", type=float, default=TIER1_LEAD_OFFSET_DEG)
    p.add_argument("--hold-max-samples", type=int, default=HOLD_MAX_SAMPLES)
    p.add_argument("--hold-flow-nudge-deg", type=float, default=HOLD_FLOW_NUDGE_DEG)
    p.add_argument("--flow-bias-nudge-deg", type=float, default=FLOW_BIAS_NUDGE_DEG)
    p.add_argument("--smoothing-alpha", type=float, default=SMOOTHING_ALPHA)
    p.add_argument("--min-moving-vel", type=float, default=2.0)
    p.add_argument("--min-agreeing-tracks", type=int, default=3)
    p.add_argument("--min-sustain-samples", type=int, default=3)
    return p.parse_args()


def main():
    args = parse_args()
    rows = run_fusion(args.tracklets, args.play_location, args)
    fieldnames = [
        "timestamp", "tier", "target_yaw", "target_yaw_smoothed", "centroid_yaw",
        "flow_direction", "flow_sustained", "flow_agreeing_tracks", "ball_conf",
        "last_ball_yaw", "samples_since_ball",
    ]
    with open(args.output, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)

    tier_counts = {1: 0, 2: 0, 3: 0, 4: 0}
    for r in rows:
        tier_counts[r["tier"]] += 1
    print(f"Wrote {args.output}: {len(rows)} rows")
    print(
        f"Tier distribution: ball-lock={tier_counts[1]} flow-hold={tier_counts[2]} "
        f"flow-only={tier_counts[3]} centroid={tier_counts[4]}"
    )


if __name__ == "__main__":
    main()
