name: Test PO token fetch (temporary)

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
      - name: Remove test download
        run: |
          rm -fv /tmp/test.mp4 /tmp/test.f315.webm /tmp/test.f251-1.webm /tmp/ytdlp.log
          df -h /
